#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────
#
# Track A: everything only the owner can do before the Soft Launch
# (.scratch/percepatan-rilis-1/plan.md, Track A; ci-cd ticket 08; prd-compliance 45).
# Run on the owner's laptop with `gh` logged in. Host steps are shown as
# commands to paste into an SSH session on the VPS; this script never touches
# the server itself, and never writes a secret into the repository.

# Secrets captured here go to a file OUTSIDE the repo, which stage 7 appends to
# the production .env on the host. Delete it once production runs.
ENV_FILE="${ENV_FILE:-$HOME/ffi-prod-additions.env}"
REPO="andrianm28/fundforindonesia.org"
KIBI_DIR="/home/ubuntu/kibi-clone"
DEPLOY_KEY="$HOME/.ssh/ffi_deploy"

gen_secret() { openssl rand -base64 32; }

TOTAL_STAGES=12
banner "Fund for Indonesia: Track A (produksi, Soft Launch)"

# ─────────────────────────────────────────────────────────────────────────
stage "Cek awal"
say "Wizard ini dijalankan di laptop Dri. Butuh: gh (login), openssl, ssh, ssh-keygen."
for tool in gh openssl ssh ssh-keygen ssh-keyscan; do
  if command -v "$tool" >/dev/null 2>&1; then note "✓ $tool"; else warn "$tool tidak ada: pasang dulu"; fi
done
if gh auth status >/dev/null 2>&1; then note "✓ gh sudah login"; else warn "gh belum login: jalankan 'gh auth login' lalu ulangi wizard"; fi
note "Nilai rahasia ditulis ke $ENV_FILE (di luar repo). Jangan commit file itu."
touch "$ENV_FILE"; chmod 600 "$ENV_FILE"
ask DEPLOY_HOST "Host/IP VPS produksi (tanpa user, mis. 203.0.113.10):"
write_env DEPLOY_HOST "$DEPLOY_HOST"
ask DEPLOY_DIR "Direktori deploy di host (mis. /srv/fundforindonesia):"
write_env DEPLOY_DIR "$DEPLOY_DIR"
pause "Tekan Enter untuk lanjut."

# ─────────────────────────────────────────────────────────────────────────
stage "A0: reviewer untuk environment production"
say "Saat ini environment 'production' tidak punya protection rule, jadi deploy"
say "bisa jalan tanpa persetujuan Dri. Tahap ini menutupnya."
open_url "https://github.com/$REPO/settings/environments"
step "Klik environment 'production' (buat bila belum ada, dengan nama persis itu)."
step "Centang 'Required reviewers', tambahkan akun Dri (andrianm28), Save protection rules."
step "Biarkan 'Prevent self-review' TIDAK dicentang bila Dri satu-satunya reviewer."
pause "Sudah disimpan? Tekan Enter."

# ─────────────────────────────────────────────────────────────────────────
stage "Sumopod QRIS: kredensial produksi"
say "Rujukan: docs/integrasi-sumopod.md. Jalur menu dashboard Sumopod tidak"
say "terdokumentasi di repo; ikuti label yang ada di dashboard proyek 'Galang Dana YIEM'."
open_url "https://sumopod.com"
step "Masuk ke proyek 'Galang Dana YIEM', mode PRODUKSI (bukan sandbox)."
step "Salin API key produksi."
ask_secret SUMOPOD_API_KEY "SUMOPOD_API_KEY (produksi):"
write_env SUMOPOD_API_KEY "$SUMOPOD_API_KEY"
step "Daftarkan webhook ke https://fundforindonesia.org/api/webhooks/sumopod, lalu salin secret-nya (berawalan whsec_)."
ask_secret SUMOPOD_WEBHOOK_SECRET "SUMOPOD_WEBHOOK_SECRET (whsec_...):"
write_env SUMOPOD_WEBHOOK_SECRET "$SUMOPOD_WEBHOOK_SECRET"
warn "Base URL API produksi Sumopod BELUM terdokumentasi. Tanyakan ke Sumopod bila tidak tertera di dashboard."
ask SUMOPOD_BASE_URL "SUMOPOD_BASE_URL produksi (mis. https://api-pay.sumopod.com/api/v1):"
write_env SUMOPOD_BASE_URL "$SUMOPOD_BASE_URL"
write_env PAYMENT_PROVIDER "sumopod"
pause "Tekan Enter untuk lanjut."

# ─────────────────────────────────────────────────────────────────────────
stage "SMTP Sumopod (email transaksional)"
say "Host, port, dan TLS sudah ditetapkan (ci-cd 08). Dri hanya mengisi akun."
write_env MAIL_PROVIDER "smtp"
write_env SMTP_HOST "smtp.sumopod.com"
write_env SMTP_PORT "465"
write_env SMTP_SECURE "true"
ask SMTP_USER "SMTP_USER:"
write_env SMTP_USER "$SMTP_USER"
ask_secret SMTP_PASSWORD "SMTP_PASSWORD:"
write_env SMTP_PASSWORD "$SMTP_PASSWORD"
ask MAIL_FROM "MAIL_FROM (mis. \"Fund for Indonesia <noreply@fundforindonesia.org>\"):"
write_env MAIL_FROM "$MAIL_FROM"
ask PARTNERSHIP_TEAM_EMAIL "PARTNERSHIP_TEAM_EMAIL (penerima Partnership Inquiry):"
write_env PARTNERSHIP_TEAM_EMAIL "$PARTNERSHIP_TEAM_EMAIL"
pause "Tekan Enter untuk lanjut."

# ─────────────────────────────────────────────────────────────────────────
stage "Secret aplikasi (dibuat otomatis)"
say "JOBS_SECRET selalu baru. NEXTAUTH_SECRET dan kunci enkripsi kolom HANYA dibuat"
say "bila .env kibi-clone belum punya. Cek di host (hanya nama kunci, bukan nilainya):"
note "  ssh ubuntu@$DEPLOY_HOST \"grep -oE '^(NEXTAUTH_SECRET|FIELD_[A-Z_]+)=' $KIBI_DIR/.env\""
write_env JOBS_SECRET "$(gen_secret)"
if confirm "NEXTAUTH_SECRET BELUM ada di .env kibi-clone?"; then
  write_env NEXTAUTH_SECRET "$(gen_secret)"
else note "NEXTAUTH_SECRET dipakai dari kibi-clone (jangan diganti: sesi login akan putus)."; fi
if confirm "FIELD_ENCRYPTION_KEY / FIELD_HMAC_KEY BELUM ada di .env kibi-clone?"; then
  write_env FIELD_ENCRYPTION_KEY "$(gen_secret)"; write_env FIELD_ENCRYPTION_KEY_ID "enc-1"
  write_env FIELD_HMAC_KEY "$(gen_secret)";       write_env FIELD_HMAC_KEY_ID "hmac-1"
  warn "Simpan salinan kedua kunci ini di password manager. Tanpa keyring, kunci yang hilang = data kontak tak terbaca (ADR 0012)."
else note "Kunci enkripsi dipakai dari kibi-clone. JANGAN ganti KEY_ID-nya (ADR 0012)."; fi
pause "Tekan Enter untuk lanjut."

# ─────────────────────────────────────────────────────────────────────────
stage "User 'deploy' dan kunci SSH khusus deploy"
if [[ ! -f "$DEPLOY_KEY" ]]; then
  ssh-keygen -t ed25519 -N "" -C "ffi-deploy-actions" -f "$DEPLOY_KEY" >/dev/null
  note "✓ kunci baru dibuat: $DEPLOY_KEY"
else note "Kunci $DEPLOY_KEY sudah ada; dipakai ulang."; fi
say "Tempel di SSH host (sebagai ubuntu/sudo):"
note "  sudo adduser --disabled-password --gecos '' deploy && sudo usermod -aG docker deploy"
note "  sudo mkdir -p $DEPLOY_DIR/ops $DEPLOY_DIR/backups $DEPLOY_DIR/logs $DEPLOY_DIR/state"
note "  sudo chown -R deploy:deploy $DEPLOY_DIR && sudo -u deploy mkdir -p ~deploy/.ssh"
say "Lalu tambahkan baris ini ke ~deploy/.ssh/authorized_keys (chmod 600, milik deploy):"
printf '  command="%s/ops/deploy.sh",no-pty,no-port-forwarding,no-agent-forwarding,no-X11-forwarding %s\n' \
  "$DEPLOY_DIR" "$(cat "$DEPLOY_KEY.pub")"
pause "Sudah dipasang di host? Tekan Enter."
say "Ambil host key. COCOKKAN fingerprint di bawah dengan yang terlihat dari konsol VPS"
say "(ssh-keygen -lf /etc/ssh/ssh_host_ed25519_key.pub di host), bukan hanya dari jaringan."
DEPLOY_KNOWN_HOSTS="$(ssh-keyscan -t ed25519 "$DEPLOY_HOST" 2>/dev/null)"
printf '%s\n' "$DEPLOY_KNOWN_HOSTS" | ssh-keygen -lf - 2>/dev/null | sed 's/^/  /'
if confirm "Fingerprint cocok dengan konsol VPS?"; then
  set_secret DEPLOY_HOST "$DEPLOY_HOST"
  set_secret DEPLOY_KNOWN_HOSTS "$DEPLOY_KNOWN_HOSTS"
  set_secret DEPLOY_SSH_KEY "$(cat "$DEPLOY_KEY")"
else
  SKIPPED+=("DEPLOY_* secrets: fingerprint belum terverifikasi")
  warn "Secret DEPLOY_* TIDAK diset. Ulangi tahap ini setelah fingerprint terverifikasi."
fi
pause "Tekan Enter untuk lanjut."

# ─────────────────────────────────────────────────────────────────────────
stage "Isi DEPLOY_DIR: file dari main, .env, login GHCR"
say "1) Salin dua file dari commit main yang akan dideploy (dari checkout lokal repo):"
note "  scp ops/deploy.sh docker-compose.prod.yml ubuntu@$DEPLOY_HOST:/tmp/"
note "  ssh ubuntu@$DEPLOY_HOST 'sudo install -o deploy -m 755 /tmp/deploy.sh $DEPLOY_DIR/ops/deploy.sh && sudo install -o deploy -m 644 /tmp/docker-compose.prod.yml $DEPLOY_DIR/'"
say "2) .env produksi = .env kibi-clone (DB_PASSWORD yang SAMA, agar volume data terbaca) + tambahan wizard:"
note "  scp $ENV_FILE ubuntu@$DEPLOY_HOST:/tmp/ffi-additions.env"
note "  ssh ubuntu@$DEPLOY_HOST 'grep -v -E \"^(DEPLOY_HOST|DEPLOY_DIR|XENDIT_[A-Z_]+)=\" /tmp/ffi-additions.env > /tmp/ffi-add.env; sudo sh -c \"cat $KIBI_DIR/.env /tmp/ffi-add.env > $DEPLOY_DIR/.env\"; sudo chown deploy:deploy $DEPLOY_DIR/.env; sudo chmod 600 $DEPLOY_DIR/.env; shred -u /tmp/ffi-additions.env /tmp/ffi-add.env'"
note "  Bila satu kunci muncul dua kali, baris terakhir yang berlaku: tambahan wizard menimpa kibi-clone."
say "3) Login GHCR dengan token read-only (classic PAT, scope read:packages saja):"
open_url "https://github.com/settings/tokens/new?scopes=read:packages&description=ffi-host-ghcr-read"
note "  ssh ubuntu@$DEPLOY_HOST 'sudo -u deploy docker login ghcr.io -u andrianm28 --password-stdin'  (tempel token, Enter, Ctrl-D)"
pause "Ketiganya selesai? Tekan Enter."

# ─────────────────────────────────────────────────────────────────────────
stage "Variabel build GitHub"
say "Dipanggang ke image saat build (cd.yml). Donasi tetap MATI sampai YIEM terdaftar (tahap 12)."
set_var NEXT_PUBLIC_BASE_URL "https://fundforindonesia.org"
set_var NEXTAUTH_URL "https://fundforindonesia.org"
set_var NEXT_PUBLIC_DONATIONS_ENABLED "false"
note "Image baru ikut variabel ini hanya setelah build berikutnya di main."
pause "Tekan Enter untuk lanjut."

# ─────────────────────────────────────────────────────────────────────────
stage "Xendit: akun sandbox (penyedia kedua)"
say "Keputusan tiket 18: Xendit. Kodenya belum ada; kunci ini disimpan untuk builder,"
say "TIDAK dimasukkan ke .env produksi. Jalur menu dashboard Xendit tidak terdokumentasi di repo."
open_url "https://dashboard.xendit.co/register"
step "Daftar atas nama PT Jaya Korpora Prima; mulai KYB (yayasan YIEM sebagai Collecting Entity)."
step "Mode TEST: buat secret API key, dan salin Callback Verification Token."
if confirm "Sudah punya kunci sandbox sekarang?"; then
  ask_secret XENDIT_SECRET_KEY "XENDIT_SECRET_KEY (test):"
  write_env XENDIT_SECRET_KEY "$XENDIT_SECRET_KEY"
  ask_secret XENDIT_CALLBACK_TOKEN "XENDIT_CALLBACK_TOKEN (test):"
  write_env XENDIT_CALLBACK_TOKEN "$XENDIT_CALLBACK_TOKEN"
else SKIPPED+=("Akun & kunci sandbox Xendit"); fi
pause "Tekan Enter untuk lanjut."

# ─────────────────────────────────────────────────────────────────────────
stage "Cutover dari kibi-clone"
warn "Tahap ini menghentikan situs lama. Kerjakan di jam sepi."
say "Urutan (rollback di setiap langkah: jalankan lagi kibi-clone dengan"
say "'cd $KIBI_DIR && docker compose up -d'; pulihkan dump bila perlu):"
step "1. Backup: ssh ubuntu@$DEPLOY_HOST \"cd $KIBI_DIR && docker compose exec -T db pg_dump -U fundindo -Fc fund_indonesia > ~/pre-cutover-\$(date -u +%Y%m%dT%H%MZ).dump\""
confirm "Backup sudah ada dan ukurannya wajar (bukan 0 byte)?" || { SKIPPED+=("Cutover: backup belum ada"); finish; exit 1; }
step "2. Stop kibi-clone (port 8093/18093 harus kosong): ssh ubuntu@$DEPLOY_HOST \"cd $KIBI_DIR && docker compose stop\""
note "   JANGAN 'down -v'. Image kibi-clone-app:latest tetap disimpan sebagai target rollback."
confirm "kibi-clone sudah berhenti?" || { SKIPPED+=("Cutover: kibi-clone belum dihentikan"); finish; exit 1; }
step "3. Deploy pertama: Actions > Deploy > Run workflow (main). Approve job 'deploy' sebagai reviewer."
open_url "https://github.com/$REPO/actions/workflows/deploy.yml"
warn "Deploy pertama DIHARAPKAN berhenti di migrasi drop_contact_plaintext bila data kontak belum di-backfill."
note "   Itu disengaja (ops/deploy.sh). Migrasi 'expand' sudah jalan dan tidak merusak kibi-clone."
step "4. Bila berhenti di sana: jalankan backfill dari checkout release ini di host, dengan .env produksi:"
note "   cd <checkout> && set -a && . $DEPLOY_DIR/.env && set +a && DATABASE_URL=postgresql://fundindo:\$DB_PASSWORD@127.0.0.1:18093/fund_indonesia npx tsx prisma/backfill-contact-fields.ts"
note "   Lalu Run workflow Deploy lagi dan approve."
step "5. Verifikasi: curl -fsS http://127.0.0.1:8093/api/health di host, lalu buka situs publik."
open_url "https://fundforindonesia.org"
confirm "Situs baru melayani lewat nginx dan /api/health 200?" || { SKIPPED+=("Cutover: verifikasi gagal, rollback ke kibi-clone"); finish; exit 1; }

# ─────────────────────────────────────────────────────────────────────────
stage "Cron untuk scheduled jobs"
say "Tanpa ini escrow tidak lepas otomatis dan pengingat tidak pernah terkirim (prd-compliance 45)."
say "Pasang di crontab user deploy (ssh ubuntu@$DEPLOY_HOST 'sudo crontab -u deploy -e'):"
printf '  */15 * * * * . "%s/.env" && curl -fsS -X POST -H "x-jobs-secret: $JOBS_SECRET" http://127.0.0.1:8093/api/internal/jobs/run >> "%s/logs/jobs.log" 2>&1\n' "$DEPLOY_DIR" "$DEPLOY_DIR"
say "Uji sekali dengan tangan, DUA kali: yang kedua harus melaporkan nol (idempoten)."
note "  401 = secret tidak cocok; 200 dengan hitungan per fase = berjalan."
pause "Cron terpasang dan uji dua kali lolos? Tekan Enter."

# ─────────────────────────────────────────────────────────────────────────
stage "Setelah deploy: YIEM, donasi ON, bersih-bersih"
step "Daftarkan YIEM sebagai Partner Organisation + Fundraising Permit (data legal asli),"
step "  lalu tetapkan sebagai Collecting Entity semua Campaign Active (percepatan-produksi 02)."
open_url "https://fundforindonesia.org/admin/collecting-entities"
confirm "YIEM terdaftar dan tidak ada Campaign Active tanpa Collecting Entity?" && {
  set_var NEXT_PUBLIC_DONATIONS_ENABLED "true"
  note "Donasi baru hidup setelah build main berikutnya + deploy (butuh approve Dri)."
}
step "Cek log: tidak ada baris 'mail_not_configured' (ssh host: docker logs <app> | grep mail_not_configured)."
step "Pastikan paket GHCR private dan tertaut ke repo."
open_url "https://github.com/andrianm28?tab=packages"
step "Hapus blok stopgap /_next/image di nginx (backup: /etc/nginx/backup-ffi-20260926/)."
step "Simpan checkout kibi-clone seminggu, lalu pensiunkan."
step "Hapus $ENV_FILE dari laptop setelah semua nilai aman di host/password manager."
pause "Tekan Enter untuk ringkasan."

finish
